---
title: 'Choose size '
author: "Andriy Koval"
output:
  html_document:
    css: ~/GitHub/Longitudinal_Models_of_Religiosity_NLSY97/www/css/thesis.css
    fig.retina: 2
  pdf_document:
    toc: yes
  word_document:
    fig_width: 6.5
---

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=F, message=F} 
require(knitr)
opts_knit$set(root.dir='../../')  #Don't combine this call with any other chunk -especially one that uses file paths.

```

```{r set_options, echo=F, message=F}
require(knitr)
# getwd()
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
#   fig.height = 4.8, 
#   fig.width = 6.5, 
  out.width = "550px",
#   fig.path = 'figure_rmd/choosingSize/',     
  dev = "png",
#   fig.path = 'figure_pdf/',     
#   dev = "pdf",
  dpi = 400
)
echoChunks <- FALSE
warningChunks<- FALSE
options(width=120) #So the output is 50% wider than the default.
```
Helps you choose the options for

+ fig.width
+ fig.height


```{r DeclareGlobals, echo=echoChunks, message=FALSE}
attcol8<-c("Never"="#4575b4",
           "Once or Twice"="#74add1",
           "Less than once/month"="#abd9e9",
           "About once/month"="#e0f3f8",
           "About twice/month"="#fee090",
           "About once/week"="#fdae61",
           "Several times/week"="#f46d43",
           "Everyday"="#d73027")

baseSize<- 14
colNA<- "#696969"
```

```{r LoadPackages, echo=echoChunks, message=F}
require(dplyr)
require(grid) #For the (zero) length of the tick marks
require(ggplot2)
```

```{r LoadData, echo=echoChunks, message=T}
dsL<-readRDS("./Data/Derived/dsL.rds")
```

```{r DefineCommonGraph, echo=echoChunks, message=F}
# The graph in this report is reproduced under various figure option conditions.
ds<- dsL %>% dplyr::filter(id==1,year %in% c(2000:2011)) %>% dplyr::select(id,year,attend) %>%
  mutate(time=year-2000)

p<-ggplot(ds, aes(x=time,y=attend, color=idF))
p<-p+ geom_line(color="purple")
# p<-p+ geom_smooth(method=lm,stat="identity", color="purple")
p<-p+ geom_point(color="purple")
p<-p+ scale_y_continuous("Church attendance",
                     limits=c(0, 8),
                     breaks=c(1:8))
p<-p+ scale_x_continuous("Years since 2000",
                   limits=c(0,11),
                   breaks=c(0:11))

# annotations
p<-p+ labs(title=paste0("In the past year, how often have you attended a worship service?"))
p<- p + guides(guide=guide_legend()) 
# themes
p <- p + ggplot2::theme_bw()
p <- p + ggplot2::theme_bw(base_size=baseSize)
p <- p + ggplot2::theme(title=ggplot2::element_text(colour="gray20",size = 12)) 
p <- p + ggplot2::theme(axis.text=ggplot2::element_text(colour="gray40"))
p <- p + ggplot2::theme(axis.title=ggplot2::element_text(colour="gray40"))
p <- p + ggplot2::theme(panel.border = ggplot2::element_rect(colour="gray80"))
p <- p + ggplot2::theme(axis.ticks.length = grid::unit(0, "cm"))
p

# p<- ggplot( ds, aes(x=yearF, y=percent, color=attendF))  #  keeping NA in calculations
# # geoms
# p<- p+ geom_line(aes(group=attendF), stat="identity", size=.7)
# p<- p+ geom_point(aes(fill=attendF), shape=21, size=3, color="black",position=position_dodge(0.2) )
# # scales
# p<- p+ scale_color_manual(values = attcol8,na.value=colNA)
# p<- p+ scale_fill_manual(values = attcol8,na.value=colNA)
# p<- p+ scale_y_continuous(limits=c(0, .4),
#                           breaks=c(.1,.2,.3,.4))
# p<- p+ scale_x_discrete(limits=as.character(c(2000:2011)))
# # # annotations
# p<- p + guides(fill = guide_legend(reverse=FALSE, title="Response category")) 
# p<- p + guides(color = FALSE) 
# p<-  p+ labs(title = "In the past year, how often have you attended a worship service?",
#                          x="Wave of measurement",
#                          y="Proportion of total")
# # # themes
# p <- p + ggplot2::theme_bw()
# p <- p + ggplot2::theme_bw(base_size=baseSize)
# p <- p + ggplot2::theme(title=ggplot2::element_text(colour="gray20",size = 12)) 
# p <- p + ggplot2::theme(axis.text=ggplot2::element_text(colour="gray40"))
# p <- p + ggplot2::theme(axis.title=ggplot2::element_text(colour="gray40"))
# p <- p + ggplot2::theme(panel.border = ggplot2::element_rect(colour="gray80"))
# p <- p + ggplot2::theme(axis.ticks.length = grid::unit(0, "cm"))
# p




height1<- 3.5
height2<- 3.8
height3<- 4
height4<- 4.2
height5<- 4.5
height6<- 4.8

width1<- 9.5
width2<- 9.5
width3<- 9.5
width4<- 9.5
width5<- 9.5
width6<- 9.5  

owidth1<- NULL
owidth2<- NULL
owidth3<- NULL
owidth4<- NULL
owidth5<- NULL
owidth6<- NULL




```


# Comparing produced graphs

##  Slot 1
```{r slot_1, echo=echoChunks, message=T,fig.height = height1, fig.width=width1, out.width=owidth1  }
p
```


##  Slot 2
```{r slot_2, echo=echoChunks, message=T, fig.height = height2, fig.width=width2, out.width=owidth2}
p
```

##  Slot 3
```{r slot_3, echo=echoChunks, message=T, fig.height = height3, fig.width=width3, out.width=owidth3}
p
```


##  Slot 4
```{r slot_4, echo=echoChunks, message=T, fig.height = height4, fig.width=width4, out.width=owidth4}
p
```


##  Slot 5
```{r slot_5, echo=echoChunks, message=T, fig.height = height5, fig.width=width5,out.width=owidth5}
p
```


##  Slot 6
```{r slot_6, echo=echoChunks, message=T, fig.height = height6, fig.width=width6, out.width=owidth6}
p
```