---
title: "lm() in mutate()"
author: "Andriy Koval"
date: "Tuesday, June 24, 2014"
output:
  pdf_document: default
  html_document:
    css: ~/GitHub/Longitudinal_Models_of_Religiosity_NLSY97/www/css/thesis.css
    fig.retina: 3
  word_document: default
---


<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=F, message=F} 
require(knitr)
opts_knit$set(root.dir='../../../')  #Don't combine this call with any other chunk -especially one that uses file paths.

```

```{r set_options, echo=F, message=F}
require(knitr)
# getwd()
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
#   fig.height = 4.8, 
#   fig.width = 6.5, 
#   out.width = "800px",
#   fig.path = 'figure_rmd/choosingSize/',     
  dev = "png",
  fig.path = 'figure_pdf/',     
#   dev = "pdf",
  dpi = 400
)
echoChunks <- FALSE
warningChunks<- FALSE
options(width=120) #So the output is 50% wider than the default.
read_chunk("./Models/Descriptives/Descriptives.R") 
```

```{r DeclareGlobals, echo=echoChunks, message=FALSE}
# Defined
attcol8 # color palette for attendance
baseSize # base text size
colNA # color for the NA value in graphs

```

```{r LoadPackages, echo=echoChunks, message=F}
```

```{r LoadData, echo=echoChunks, message=T}
# select only respondence in the cross-sectional sample

```

Data for a single person
```{r, echo=T,eval=TRUE, message=T}
ds<- dsL %>% dplyr::filter(id==1,year %in% c(2000:2011)) %>% dplyr::select(id,year,attend) %>%
  mutate(time=year-2000)
print(ds)
```

```{r}
ds <- read.table(header = TRUE, text ="
obs  id year attend
1  47 2000      1
2  47 2001      3
3  47 2002      5
4  47 2003      8
5  47 2004      6
6  47 2005      4
7  47 2006      2
8  47 2007      1
9  47 2008      2
10 47 2009      3
11 47 2010      4
12 47 2011      5

")
ds<- ds %>% dplyr::mutate(time=year-2000)
print(ds)

```


```{r, echo=F}
require(ggplot2)
p<-ggplot(ds, aes(x=time,y=attend, color=idF))
p<-p+ geom_line(color="purple")
# p<-p+ geom_smooth(method=lm,stat="identity", color="purple")
p<-p+ geom_point(color="purple")
p<-p+ scale_y_continuous("Church attendance",
                     limits=c(0, 8),
                     breaks=c(1:8))
p<-p+ scale_x_continuous("Years since 2000",
                   limits=c(0,11),
                   breaks=c(0:11))

# annotations
p<-p+ labs(title=paste0("In the past year, how often have you attended a worship service?"))
p<- p + guides(color = guide_legend(title="Respondents")) 
# themes
p <- p + ggplot2::theme_bw()
p <- p + ggplot2::theme_bw(base_size=baseSize)
p <- p + ggplot2::theme(title=ggplot2::element_text(colour="gray20",size = 12)) 
p <- p + ggplot2::theme(axis.text=ggplot2::element_text(colour="gray40"))
p <- p + ggplot2::theme(axis.title=ggplot2::element_text(colour="gray40"))
p <- p + ggplot2::theme(panel.border = ggplot2::element_rect(colour="gray80"))
p <- p + ggplot2::theme(axis.ticks.length = grid::unit(0, "cm"))
p
```


add a straight line to represent possible predition line, in this case a straight line
```{r}
linear<- predict(lm(attend ~ time, ds))
ds<- ds %>% dplyr::mutate(linear=linear)
print(ds)
p<-p+ geom_line(aes(y=linear),color="red", size=.5)
p
```
Or adding the curvarture the  quadratic term
```{r}
quadratic<- predict(lm(attend ~ poly(time,2),ds))
ds<- ds %>% mutate(quadratic=quadratic)
print(ds)
p<-p+ geom_line(aes(y=quadratic),color="blue", size=.5)
 p
# p<-p+ geom_line(aes(y=cubic),color="green", size=.5)
```
or the cubic term
```{r}
cubic<- predict(lm(attend ~ poly(time,3),ds))
ds<- ds %>% mutate( cubic=cubic)
print(ds)
p<-p+ geom_line(aes(y=cubic),color="green", size=.5)
p
```




