---
title: "Single model"
output:
  html_document:
    css: ~/GitHub/Longitudinal_Models_of_Religiosity_NLSY97/www/css/thesis.css
    fig.retina: 2
    fig_width: 8
    toc: yes
  md_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    fig_crop: no
    fig_width: 8
    highlight: haddock
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 3
  word_document:
    fig_width: 6.5
mainfont: Calibri
---

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=F, message=F} 
require(knitr)
opts_knit$set(root.dir='../../')  #Don't combine this call with any other chunk -especially one that uses file paths.

```

```{r set_options, echo=F, message=F}
require(knitr)
# getwd()
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
#   fig.height = 4.8, 
#   fig.width = 6.5, 
#   out.width = NULL,
  fig.path = 'sequence/',     
  dev = "png",
  dpi = 100
)
echoChunks <- FALSE
warningChunks<- FALSE
options(width=120) #So the output is 50% wider than the default.
read_chunk("./Models/LCM/sequenceLCM.R") # the file to which knitr calls for the chunks
```

```{r DeclareGlobals, echo=echoChunks, message=FALSE}
aesDefs
```

```{r LoadPackages, echo=echoChunks, message=F}
```

```{r LoadData, echo=echoChunks, message=T}
# select only respondence in the cross-sectional sample

```

```{r}
cat("\014") # clears console
modelNumber<- "m10"
numID<- 9022

modnum<-cat(modelNumber)
dsL<-readRDS("./Data/Derived/dsL.rds")
ds<- dsL %>%  # chose conditions to apply in creating dataset for modeling
  dplyr::filter(id %in% c(1:numID)) %.% # 1:9022
  dplyr::filter(year %in% c(2000:2011)) %.% # 1997:2011
  dplyr::filter(sample %in% c(1)) %.% # 0-Oversample; 1-Cross-Sectional
  dplyr::filter(race %in% c(4)) %.% # 1-Black; 2-Hispanis; 3-Mixed; 4-White
  dplyr::filter(byear %in% c(1980:1984)) %.% # birth year 1980:1984
#   dplyr::filter(ave(!is.na(attend), id, FUN = all)) %.% # remove ids with NA
  dplyr::mutate( # create new variables
        age= year-byear, # definition of age to be used in the model    
#         timec=year-2000, # metric of time is rounds of NSLY97 in years, centered at 2000
#         timec2= timec^2, 
#         timec3= timec^3,
        timec= age-16, # metric of time is bilogical age in years, centered at 16
        timec2= timec^2,
        timec3= timec^3,# 
        cohort=byear-1980) %.% # age difference, years younger
  dplyr::select( # assemble the dataset for modeling
    id, sample, race, byear,cohort, # Time Invariant variables
    year,
    age, timec,timec2,timec3, attend)  # Time Variant variables
head(ds)
cat(length(unique(ds$id))) # total No. of respondents in dataset
sum(!is.na(ds$attend)) # total No. of valid datapoints 
sum(is.na(ds$attend)) # total No. of missing values 
# Counts of observations at each time point
table(ds["year"]) # Number of respondent in each NLSY97 round  

# two way table with marginal counts of non-missing attend values
ds %>% dsL %>% group_by(id) %>% filter(sum(is.na(attend)) == 0)
ds


table(ds$year,is.na(ds$attend))

table(ds$age,is.na(ds$attend))

table(round(ds$age,0)) # Number of respondents in each age bin

group_by(ds,year) %.% summarize(length(attend))

table(ds$age,ds$year,!is.na(ds$attend))

table(ds$byear,ds$age,!is.na(ds$attend))

table(ds$byear)/length(unique(ds$year))# Counts for the year of birth  - metric: YEAR 

table(ds$sample, ds$race)/length(unique(ds$year)) # Sample BY Race counts

# # Estimate the model
# modnum <-lmer (attend ~ 
#                1  + timec + timec2 + timec3
#        + cohort + cohort:timec + cohort:timec2 + cohort:timec3
#               + (1 | id),
#              data = ds, REML=FALSE, 
#              control=lmerControl(optCtrl=list(maxfun=20000)))
#         
# model<- modnum
# summary(model)
```

# m7R
```{r m7R}

```

