Descriptive statistics
=================================================
This report tracks down the visualizations of the NLSY97 religiosity data as defined by the extract NLSY97_Religiosity_20042014 


<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=T, message=F} 
opts_knit$set(root.dir='../')  #Don't combine this call with any other chunk -especially one that uses file paths.
getwd()
```


<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=T, message=T}
require(knitr)
opts_chunk$set(root.dir="../",
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  fig.height = 4, 
  fig.width = 5.5, 
  out.width = "550px",
  fig.path = 'figure_rmd/',     
  dev = "png",
#   fig.path = 'figure_pdf/',     
#   dev = "pdf",
  dpi = 400
)
echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.
read_chunk("./Descriptives/Descriptives.R") # the file to which knitr calls for the chunks
getwd()
```

```{r DeclareGlobals, echo=echoChunks, message=FALSE}
```

```{r LoadData, echo=echoChunks, message=FALSE}
```

```{r LoadPackages, echo=echoChunks, message=FALSE}
```

```{r TweakData, echo=echoChunks, message=FALSE}
```

```{r AnalysisChunk01, echo=echoChunks, message=FALSE}
```

